### ISSUE TITLE
Reply to message pulls a different message than the one selected

### ISSUE THREAD

**Issue by pquesinb** [mt-mods/mail#61] opened 2023-04-10 17:57 UTC
Hitting reply includes the subject and message text of a different message than the one you're actually replying to... it appears to be related to how many messages are in the list, could be 8 or 10, 11, 12 messages down from the one selected.  It also appears to do the same thing if you delete a message while you're reading it, it deletes a different message.  Deleting a message from a message list window works properly (I think).

Also, the Close button doesn't work, I have to hit Esc to exit the mail system.

Thanks!

**Comment by S-S-X** [comment] 2023-04-10 18:04
Would be good to add some tests for this.

**Comment by pquesinb** [comment] 2023-04-10 19:39
Ok, I've confirmed that it appears to work properly if you delete the message from the message list (inbox).

In order to verify behavior:

Send a test message to yourself

If you then select/highlight newly received message from inbox list without opening it:
Hit 'Reply'
Correct message appears to reply to in input/edit box.

If you open newly received message:
Hit 'Reply' while message is being displayed
Wrong/different message appears to reply to in input/edit box

Thanks for looking into this.  Let me know if you need any additional info and thanks again.

\- Phil

**Comment by Athozus** [comment] 2023-04-11 09:27
Hi, thx for reporting the issue. Are you using a release or the latest commit on `master` branch ?

**Comment by Athozus** [comment] 2023-04-11 09:38
If you're using sorters/filters, it's probably due to :

https://github.com/mt-mods/mail/blob/67bda9a788f96dfcc6b6a421445d023fb6dbe5f8/ui/message.lua#L95-L96

Which doesn't use the sorted and filtered list. I will fix it later.

**Comment by pquesinb** [comment] 2023-04-11 15:59
Using latest git pull from master.

Guessing that's probably it (I'm a programmer but don't know enough lua to be useful).  I figured it was either using different code to index into the messages or a variable used for that purpose was being corrupted by the editor.

Thanks again for all of the hard work.

\- Phil

**Comment by pquesinb** [comment] 2023-04-19 03:44
It works fine in the inbox now (thanks for the fix!) but replying to a message in "Sent messages" exhibits the same behavior.

**Comment by Athozus** [comment] 2023-04-19 08:14
I will work on that, thx

**Comment by Athozus** [comment] 2023-04-20 06:49
Hi !

I presume you were using the "Read" button, not the double-click ? If you used the button, then this commit should fix the issue : 2290c28.

Please pull from `master` branch then tell me your feedback ;)

**Comment by pquesinb** [comment] 2023-04-20 20:25
After latest git pull from master,  'git log' shows:
commit 2290c2838e378d37aa9c4b56d20700047847b890 (HEAD -> master, origin/master, origin/HEAD)
Author: Athozus <athozus@gmail.com>
Date:   Thu Apr 20 08:47:59 2023 +0200

    Fix wrong message view in outbox
...

If I go to sent mail and pull up the message, by either double-clicking or via the "Read" button, it shows the correct message, but if you then do a "Reply" or "Reply All", it pulls the wrong message (the next message down in the list in the subsequent tests).

The first time I tried though, it apparently tried to index a message that didn't exist, and crashed due to the null/nil value:

2023-04-20 15:56:56: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'mail' in callback on_playerReceiveFields(): ...s/minetest-server/.minetest/mods/mail_mod/ui/message.lua:48: attempt to index local 'message' (a nil value)
2023-04-20 15:56:56: ERROR[Main]: stack traceback:
2023-04-20 15:56:56: ERROR[Main]: 	...s/minetest-server/.minetest/mods/mail_mod/ui/message.lua:48: in function 'reply'
2023-04-20 15:56:56: ERROR[Main]: 	...s/minetest-server/.minetest/mods/mail_mod/ui/message.lua:105: in function <...s/minetest-server/.minetest/mods/mail_mod/ui/message.lua:87>
2023-04-20 15:56:56: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/register.lua:431: in function </usr/local/share/minetest/builtin/game/register.lua:417>

**Comment by pquesinb** [comment] 2023-04-21 19:13
Hi Athozus,

No problem.

I forgot to mention that just as before, if you highlight the message and hit 'Reply' or 'Reply All', then it works properly but if you open the message and then hit either of those buttons then you get the wrong message or a crash, presumably depending upon which message is being indexed/pointed to.

Unfortunately, same behavior as before:

Cloned from fix/messages-info.  'git log' shows:
commit b2189ef041e76e7a672398557993fa3cdd98a1ec (HEAD -> fix/message-infos, origin/fix/message-infos)
Author: Athozus <athozus@gmail.com>
Date:   Thu Apr 20 21:24:11 2023 +0200

    Fix weird showing of message informations in outbox.lua

--

2023-04-21 14:59:36: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'mail' in callback on_playerReceiveFields(): ...games/minetest-server/.minetest/mods/mail/ui/message.lua:48: attempt to index local 'message' (a nil value)
2023-04-21 14:59:36: ERROR[Main]: stack traceback:
2023-04-21 14:59:36: ERROR[Main]: 	...games/minetest-server/.minetest/mods/mail/ui/message.lua:48: in function 'reply'
2023-04-21 14:59:36: ERROR[Main]: 	...games/minetest-server/.minetest/mods/mail/ui/message.lua:105: in function <...games/minetest-server/.minetest/mods/mail/ui/message.lua:87>
2023-04-21 14:59:36: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/register.lua:431: in function </usr/local/share/minetest/builtin/game/register.lua:417>

**Comment by Athozus** [comment] 2023-04-21 20:26
Oh okay, thx, I understand better now, I will fix that.

**Comment by Athozus** [comment] 2023-04-21 20:28
Please pull again from my fork, same branch, it would be fixed. For me it is ok.

**Comment by pquesinb** [comment] 2023-04-21 20:46
Yup... FIXED.  Looks like it's working properly now.

Thanks a bunch!

**Comment by pquesinb** [comment] 2023-04-23 03:00
I spoke too soon.

Another player complained that he couldn't reply to my messages, that it was crashing the server.  He had to leave a new message instead.  Attempting to reply generated the following, including after the latest git pull from your fix/message-infos branch.

2023-04-22 22:52:33: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'mail' in callback on_playerReceiveFields(): ...games/minetest-server/.minetest/mods/mail/ui/message.lua:48: attempt to concatenate field 'body' (a nil value)
2023-04-22 22:52:33: ERROR[Main]: stack traceback:
2023-04-22 22:52:33: ERROR[Main]: 	...games/minetest-server/.minetest/mods/mail/ui/message.lua:48: in function 'reply'
2023-04-22 22:52:33: ERROR[Main]: 	...games/minetest-server/.minetest/mods/mail/ui/message.lua:105: in function <...games/minetest-server/.minetest/mods/mail/ui/message.lua:87>
2023-04-22 22:52:33: ERROR[Main]: 	/usr/local/share/minetest/builtin/game/register.lua:431: in function </usr/local/share/minetest/builtin/game/register.lua:417>

Let me know if I can provide any additional info or if you want me to test anything else.

\- Phil

**Comment by S-S-X** [comment] 2023-04-23 03:32
Enough reopens to give a reminder about #70

**Comment by Athozus** [comment] 2023-04-23 07:49
Hi !

Sorry for the crashes again, do you have any additional infos (inbox/outbox,...) ?

Hope this will be definitely fixed, it should be trivial as always.

**Comment by pquesinb** [comment] 2023-04-23 16:08
Now I can't reproduce the problem, I wanted to see if it was the same as before where it worked if you hit the action button (i.e. Reply) in the message list instead of in the editor after opening the message.

If I'm able to reproduce it I'll reopen.  From the error it looks like the message body is a null value this time but again, unfortunately I don't know enough Lua to be useful.  I can do simple LuaController programs and that's about it.   :)

**Comment by pquesinb** [comment] 2023-04-23 19:51
Success!  (Well, if a crash is a success...)

I've recreated the problem and have confirmed that, in fact, highlighting a message in the inbox list and hitting 'Reply' works fine, while opening the message and then hitting 'Reply' causes the crash.  So... looks like the same sort of thing going on as before, just in a different area.

Don't you just love open-source?  You make all of these cool enhancements and people just complain...   :)

**Comment by Athozus** [comment] 2023-04-26 07:58
This is due to a bug in `message.lua`, something like if the selection had disappeared while loading `message.lua`. The problem is that only the body is impacted.

**Comment by Athozus** [comment] 2023-04-26 08:26
It is strange it is like the data disappear while passing in the first `if then`.

**Comment by Athozus** [comment] 2023-04-26 09:00
Update : `mail.selected_idxs.boxtab[name]` is storing data for the outbox (`2` value), but not for inbox (`1` value).

**Comment by pquesinb** [comment] 2023-04-26 16:05
Just pulled the latest and tested and it appears to be fixed now!

There was another issue where if you opened mail and immediately hit reply from the inbox without selecting a message it would crash with a null index but that appears to be fixed as well.  Many thanks for fixing this and for the explanation of what was actually going on.

Now if someone could recommend a good text or online course/tutorial on Lua I'd be eternally grateful.  Preferably aimed at someone who's an experienced programmer but completely inexperienced (i.e. clueless) with Lua.  I'd really like the possibility of being able to contribute more in the future, I love mysteries.  :)

Thanks again, and keep up the great work!

\- Phil

**Comment by S-S-X** [comment] 2023-04-26 16:33
> Now if someone could recommend a good text or online course/tutorial on Lua I'd be eternally grateful. Preferably aimed at someone who's an experienced programmer but completely inexperienced (i.e. clueless) with Lua.

Lua book and Lua reference manual are actually very good resources, especially if you're already familiar with some other programming languages.
Reference manual: https://www.lua.org/manual/5.1/manual.html
Book: https://www.lua.org/pil/contents.html (note that free book is written for 5.0 but is mostly good for later versions too)

Then if thinking about Minetest modding there's few resources useful resources for that:
Minetest Lua API: https://raw.githubusercontent.com/minetest/minetest/5.7.0/doc/lua_api.txt
Formatted modding API: https://minetest.gitlab.io/minetest/
Minetest modding book: https://rubenwardy.com/minetest_modding_book

**Comment by Athozus** [comment] 2023-04-26 16:34
> Just pulled the latest and tested and it appears to be fixed now!
> 
> There was another issue where if you opened mail and immediately hit reply from the inbox without selecting a message it would crash with a null index but that appears to be fixed as well. Many thanks for fixing this and for the explanation of what was actually going on.

Good so

> Now if someone could recommend a good text or online course/tutorial on Lua I'd be eternally grateful. Preferably aimed at someone who's an experienced programmer but completely inexperienced (i.e. clueless) with Lua. I'd really like the possibility of being able to contribute more in the future, I love mysteries. :)

It is a bit offtopic, but maybe you could like : 

* https://www.tutorialspoint.com/lua/
* https://en.wikibooks.org/wiki/Lua_Programming

> Thanks again, and keep up the great work!
> 
> - Phil

Yw =) -- Athozus

**Comment by pquesinb** [comment] 2023-05-08 16:38
Now that I need to reopen this issue, let me first say many thanks for all of the info above.

Looks like this bug refuses to die... got this when replying to an email from another player last night:

2023-05-07 18:46:49: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'mail' in callback on_playerReceiveFields(): ...s/minetest-server/.minetest/mods/mail_mod/ui/messa
ge.lua:48: attempt to index local 'message' (a nil value)
2023-05-07 18:46:49: ERROR[Main]: stack traceback:
2023-05-07 18:46:49: ERROR[Main]:       ...s/minetest-server/.minetest/mods/mail_mod/ui/message.lua:48: in function 'reply'
2023-05-07 18:46:49: ERROR[Main]:       ...s/minetest-server/.minetest/mods/mail_mod/ui/message.lua:105: in function <...s/minetest-server/.minetest/mods/mail_mod/ui/message.lua:87>
2023-05-07 18:46:49: ERROR[Main]:       /usr/local/share/minetest/builtin/game/register.lua:431: in function </usr/local/share/minetest/builtin/game/register.lua:417>

I did another git pull after this and there was a pretty big update but it appeared to be mainly README and translation updates along with the addition of a notification sound - nothing I saw that would fix the above.

I couldn't reproduce the crash but it looks like more of the same null pointer stuff so I wanted to make sure you knew about it.

Thanks again,

\- Phil

**Comment by Athozus** [comment] 2023-05-08 16:52
Ok thx. So, you was in inbox right ? What was the commit id when your crash occurred (before you pulled) ? Were some fields of the message empty ?

**Comment by pquesinb** [comment] 2023-05-08 20:35
Actually it had opened the message and hit reply after viewing it - that's when it crashed.  The CC and BCC fields were empty but it had a subject and body/message text.

I wasn't sure which commit it was but according to git reflog it was 5e3cfed, there had been a couple of updates after you had fixed the last issue I reported so that sounds about right.  I thought that I was still on your "fix/message-infos" branch but either I or one of the commits changed it back to master.

root@racknerd-xxxxxx:/var/games/minetest-server/.minetest/mods/mail_mod# git reflog
8dcfc7d (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: pull --stat: Fast-forward
5e3cfed HEAD@{1}: pull --stat: Fast-forward
a863225 (tag: 1.1.4) HEAD@{2}: pull --stat: Fast-forward
47b18f2 HEAD@{3}: pull --stat: Fast-forward
7449aac HEAD@{4}: pull --stat: Fast-forward
...

**Comment by Athozus** [comment] 2023-05-09 06:30
Ok so you think that it is fixed. And concerning what you said, did you pushed Reply in inbox or in message view ? And reply or reply all ?

**Comment by pquesinb** [comment] 2023-05-09 16:06
I suppose it's possible that it's been fixed but I doubt it, looks like only translation and sound enhancements since 5e3cfed.

I can't seem to duplicate the crash now though so I can't give you any more useful information to find the bug if it's still present.  I'll keep trying from time to time though in case conditions might later be right to make it crash again.

\- Phil

**Comment by pquesinb** [comment] 2023-05-09 16:54
I hit 'Reply' while in the message view when it crashed.  Generally that's when these crashes occur, highlighting a message in the inbox list doesn't usually cause these crashes... it's normally when you hit reply while viewing the message.

**Comment by Athozus** [comment] 2023-05-20 18:21
I still don't have that bug o_O

**Comment by BuckarooBanzay** [comment] 2023-05-20 18:56
> it's normally when you hit reply while viewing the message.

pretty sure this is a duplicate of #84

IMO: this can be closed, and a temporary workaround has already been pushed in `master`

**Comment by Athozus** [comment] 2023-05-20 19:28
Which one ? #84 or #61 (61 is the oldest so it might be the one still open)

**Comment by BuckarooBanzay** [comment] 2023-05-20 19:35
most data has been collected in #84 this with started with something else i think

**Comment by Athozus** [comment] 2023-05-20 19:49
Ok so I close, according to @BuckarooBanzay suggestion =)

**Closed by Athozus** 2023-05-20 19:49 UTC
Labels: bug
